// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO;

public partial class Agreement
{
    public string AgreementId { get; set; }

    public string CustomerId { get; set; }

    public string Spid { get; set; }

    public string CreditId { get; set; }

    public string DealerCarId { get; set; }

    public string Loiid { get; set; }

    public string MethodPayment { get; set; }

    public DateOnly AgreementDate { get; set; }

    public virtual Credit Credit { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual DealerCar DealerCar { get; set; }

    public virtual LetterOfIntent Loi { get; set; }

    public virtual OtherBenefit OtherBenefit { get; set; }

    public virtual ICollection<PaymentHistory> PaymentHistories { get; set; } = new List<PaymentHistory>();

    public virtual SalesPerson Sp { get; set; }

    public virtual Warranty Warranty { get; set; }
}