// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO;

public partial class Car
{
    public string CarId { get; set; }

    public string ModelType { get; set; }

    public string FuelType { get; set; }

    public int BasePrice { get; set; }

    public int Stock { get; set; }

    public virtual ICollection<DealerCar> DealerCars { get; set; } = new List<DealerCar>();
}