// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO;

public partial class Consultation
{
    public string ConsultId { get; set; }

    public int? ScheduleId { get; set; }

    public string Spid { get; set; }

    public int CustomerBudget { get; set; }

    public DateTime ConsultDate { get; set; }

    public string Note { get; set; }

    public virtual Scheduling Schedule { get; set; }

    public virtual SalesPerson Sp { get; set; }

    public virtual ICollection<TestDrive> TestDrives { get; set; } = new List<TestDrive>();
}