// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO;

public partial class Credit
{
    public string CreditId { get; set; }

    public string CustomerId { get; set; }

    public int NominalKredit { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public int Bunga { get; set; }

    public int MonthlyPayment { get; set; }

    public string StatusCredit { get; set; }

    public virtual ICollection<Agreement> Agreements { get; set; } = new List<Agreement>();

    public virtual Customer Customer { get; set; }
}