// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO;

public partial class Customer
{
    public string CustomerId { get; set; }

    public string Tdid { get; set; }

    public string IdCardNumber { get; set; }

    public virtual ICollection<Agreement> Agreements { get; set; } = new List<Agreement>();

    public virtual ICollection<Credit> Credits { get; set; } = new List<Credit>();

    public virtual ICollection<OrderCust> OrderCusts { get; set; } = new List<OrderCust>();

    public virtual TestDrive Td { get; set; }
}