// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO;

public partial class Dealer
{
    public string DealerId { get; set; }

    public string DealerName { get; set; }

    public string DealerAddress { get; set; }

    public string City { get; set; }

    public string Province { get; set; }

    public int TaxRate { get; set; }

    public virtual ICollection<DealerCar> DealerCars { get; set; } = new List<DealerCar>();

    public virtual ICollection<SalesPerson> SalesPeople { get; set; } = new List<SalesPerson>();

    public virtual ICollection<Scheduling> Schedulings { get; set; } = new List<Scheduling>();
}