// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO;

public partial class DealerCar
{
    public string DealerCarId { get; set; }

    public string CarId { get; set; }

    public string DealerId { get; set; }

    public int DealerCarPrice { get; set; }

    public virtual ICollection<Agreement> Agreements { get; set; } = new List<Agreement>();

    public virtual Car Car { get; set; }

    public virtual Dealer Dealer { get; set; }

    public virtual ICollection<OrderCust> OrderCusts { get; set; } = new List<OrderCust>();

    public virtual ICollection<TestDrive> TestDrives { get; set; } = new List<TestDrive>();
}