// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO;

public partial class Guest
{
    public int GuestId { get; set; }

    public string GuestName { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public virtual ICollection<Scheduling> Schedulings { get; set; } = new List<Scheduling>();
}