// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO;

public partial class LetterOfIntent
{
    public string Loiid { get; set; }

    public int BookingFee { get; set; }

    public virtual Agreement Agreement { get; set; }

    public virtual ICollection<OrderCust> OrderCusts { get; set; } = new List<OrderCust>();
}