// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO;

public partial class OrderCust
{
    public string Ocid { get; set; }

    public string CustomerId { get; set; }

    public string Dcid { get; set; }

    public string Loiid { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual DealerCar Dc { get; set; }

    public virtual LetterOfIntent Loi { get; set; }
}