// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO;

public partial class SalesPerson
{
    public string Spid { get; set; }

    public string SalesName { get; set; }

    public string DealerId { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public virtual ICollection<Agreement> Agreements { get; set; } = new List<Agreement>();

    public virtual ICollection<Consultation> Consultations { get; set; } = new List<Consultation>();

    public virtual Dealer Dealer { get; set; }

    public virtual ICollection<TestDrive> TestDrives { get; set; } = new List<TestDrive>();
}