// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO;

public partial class Scheduling
{
    public int ScheduleId { get; set; }

    public int GuestId { get; set; }

    public string DealerId { get; set; }

    public string Program { get; set; }

    public DateTime AvailableStart { get; set; }

    public DateTime AvailableEnd { get; set; }

    public virtual Consultation Consultation { get; set; }

    public virtual Dealer Dealer { get; set; }

    public virtual Guest Guest { get; set; }

    public virtual TestDrive TestDrive { get; set; }
}