// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.BO;

public partial class TestDrive
{
    public string Tdid { get; set; }

    public string ConsultId { get; set; }

    public int? ScheduleId { get; set; }

    public string DealerCarId { get; set; }

    public string Spid { get; set; }

    public string Note { get; set; }

    public DateTime Tddate { get; set; }

    public virtual Consultation Consult { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual DealerCar DealerCar { get; set; }

    public virtual Scheduling Schedule { get; set; }

    public virtual SalesPerson Sp { get; set; }
}